spring.application.name=ms-01-eureka-server

# Puerto estandar para Eureka
server.port=8761

# Configuraciones para que el servidor no actue como cliente de si mismo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Configuracion de log para ver cuando los microservicios se registran o se eliminan del servidor Eureka
logging.level.com.netflix.discovery=INFO
logging.level.com.netflix.eureka=INFO