# Perfil Docker - Sobrescribe localhost con nombres de contenedores

spring.datasource.url=jdbc:mysql://mysql-db:3306/db_categories
spring.datasource.username=root
spring.datasource.password=root

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
